- name: Set localhost to 127.0.0.1
  copy:
    src: /tmp/hosts
    dest: /etc/hosts

- name: Add banner strings
  copy:
    dest: /etc/motd
    content: |
      .    _______.____    ____  __      ____    ____  ___       __  .__   __. 
      .   /       |\   \  /   / |  |     \   \  /   / /   \     |  | |  \ |  | 
      .  |   (----` \   \/   /  |  |      \   \/   / /  ^  \    |  | |   \|  | 
      .   \   \      \_    _/   |  |       \      / /  /_\  \   |  | |  . `  | 
      .----)   |       |  |     |  `----.   \    / /  _____  \  |  | |  |\   | 
      |_______/        |__|     |_______|    \__/ /__/     \__\ |__| |__| \__| 
                                                                              
      .______       ___________    ____ .__   __.      ___      __    __   _______  
      |   _  \     |   ____\   \  /   / |  \ |  |     /   \    |  |  |  | |       \ 
      |  |_)  |    |  |__   \   \/   /  |   \|  |    /  ^  \   |  |  |  | |  .--.  |
      |      /     |   __|   \_    _/   |  . `  |   /  /_\  \  |  |  |  | |  |  |  |
      |  |\  \----.|  |____    |  |     |  |\   |  /  _____  \ |  `--'  | |  '--'  |
      | _| `._____||_______|   |__|     |__| \__| /__/     \__\ \______/  |_______/


- name: Set DNS to Google DNS
  copy:
    src: /tmp/resolv.conf
    dest: /etc/resolv.conf

- name: Add web app
  copy:
    src: /tmp/app.jar
    dest: /opt/app.jar

- name: Add app service
  copy:
    src: /tmp/app.service
    dest: /etc/systemd/system/app.service

- name: Install openjdk-17-jdk ignoring "install-recommends"
  apt:
    name: openjdk-17-jdk
    update_cache: yes
    install_recommends: no

- name: Restart app service
  systemd:
    name: app.service
    state: restarted
